apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: example-mysql-cluster-expose-enable-ops
spec:
  type: Expose
  clusterName: semisync-mysql-cluster
  expose:
  - componentName: mysql
    services:
    - name: internet
      # Valid options are 'ClusterIP', 'NodePort', and 'LoadBalancer'.
      serviceType: NodePort
      # Contains cloud provider related parameters if ServiceType is LoadBalancer.
      #annotations:
        #service.beta.kubernetes.io/aws-load-balancer-type: nlb
        #service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      # Specifies a role to target with the service.
      # If specified, the service will only be exposed to pods with the matching role.
      roleSelector: primary
    switch: Enable
